/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hfeng' at '15-4-25 下午12:08' with Gradle 2.3
 *
 * @author hfeng, @date 15-4-25 下午12:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
